from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Sequence, Tuple, Union
import ast
import json
import re

import networkx as nx
import numpy as np
import pandas as pd


_NUMPY_WRAPPER_RE = re.compile(
    r"np\.(?:float64|float32|int64|int32)\(([-+0-9.eE]+)\)"
)


def _clean_numpy_wrappers(value: str) -> str:
    """Convert simple textual np.float64(...)/np.int64(...) wrappers to literals."""
    return _NUMPY_WRAPPER_RE.sub(r"\1", value)


def _parse_structured(value: Any) -> Any:
    """Parse JSON first, then Python literals for backward compatibility."""
    if isinstance(value, (list, dict, tuple)):
        return value
    if value is None or (isinstance(value, float) and np.isnan(value)):
        raise ValueError("Missing structured CSV value.")

    text = _clean_numpy_wrappers(str(value).strip())
    if not text:
        raise ValueError("Empty structured CSV value.")

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return ast.literal_eval(text)


def _get_float(mapping: Dict[str, Any], keys: Sequence[str]) -> float:
    for key in keys:
        if key in mapping and mapping[key] is not None:
            return float(mapping[key])
    raise KeyError(f"None of the required keys exists: {list(keys)}")


@dataclass(frozen=True)
class DAGRecord:
    csv_path: str
    row_index: int
    num_subtasks: int
    edges: List[Tuple[int, int]]
    characteristics: List[Dict[str, Any]]


class CreateDAG:
    """
    Parse one DAG row and expose the task profiles used by the scheduler.

    Processor convention retained from the original project/dataset:
        proc1 = A12
        proc2 = A7

    The parser accepts the project's v_f_levels format generated by
    gen_dataset.py and extracts the highest-frequency A7/A12 profile.
    """

    def __init__(
        self,
        csv_path: Union[str, Path],
        row_index: int = 0,
    ) -> None:
        record = self.read_record(csv_path, row_index)

        self.csv_path = record.csv_path
        self.row_index = record.row_index
        self.num_subtasks = record.num_subtasks
        self.edges = record.edges
        self.characteristics = record.characteristics

        self.graph = nx.DiGraph()
        self.graph.add_nodes_from(range(self.num_subtasks))
        self.graph.add_edges_from(self.edges)

        if not nx.is_directed_acyclic_graph(self.graph):
            raise ValueError("Input graph is not a DAG.")

        self.periods: List[float] = []
        self.deadlines: List[float] = []
        self.m_i_list: List[int] = []

        self.a7_times: List[float] = []
        self.a12_times: List[float] = []
        self.a7_powers: List[float] = []
        self.a12_powers: List[float] = []
        self.a7_energy: List[float] = []
        self.a12_energy: List[float] = []

        self._parse_characteristics()

    @staticmethod
    def read_record(
        csv_path: Union[str, Path],
        row_index: int = 0,
    ) -> DAGRecord:
        csv_path = Path(csv_path)
        if not csv_path.exists():
            raise FileNotFoundError(f"Dataset CSV not found: {csv_path}")

        frame = pd.read_csv(csv_path)
        if frame.empty:
            raise ValueError(f"Dataset is empty: {csv_path}")
        if not 0 <= int(row_index) < len(frame):
            raise IndexError(
                f"row_index={row_index} is outside 0..{len(frame) - 1} for {csv_path}"
            )

        row = frame.iloc[int(row_index)]
        num_subtasks = int(row["num_subtasks"])
        characteristics_raw = _parse_structured(row["characteristics"])
        edges_raw = _parse_structured(row["edges"])

        if not isinstance(characteristics_raw, list):
            raise TypeError("characteristics must decode to a list.")
        if len(characteristics_raw) != num_subtasks:
            raise ValueError(
                f"characteristics length={len(characteristics_raw)} does not match "
                f"num_subtasks={num_subtasks}."
            )

        edges: List[Tuple[int, int]] = []
        for item in edges_raw:
            if not isinstance(item, (list, tuple)) or len(item) != 2:
                raise ValueError(f"Invalid edge entry: {item!r}")
            source, target = int(item[0]), int(item[1])
            if not (0 <= source < num_subtasks and 0 <= target < num_subtasks):
                raise ValueError(f"Edge endpoint out of range: {(source, target)}")
            if source == target:
                raise ValueError(f"Self-loop is not allowed in a DAG: {(source, target)}")
            edges.append((source, target))

        graph = nx.DiGraph()
        graph.add_nodes_from(range(num_subtasks))
        graph.add_edges_from(edges)
        if not nx.is_directed_acyclic_graph(graph):
            raise ValueError(f"Row {row_index} in {csv_path} contains a cyclic graph.")

        characteristics = [dict(item) for item in characteristics_raw]
        return DAGRecord(
            csv_path=str(csv_path),
            row_index=int(row_index),
            num_subtasks=num_subtasks,
            edges=edges,
            characteristics=characteristics,
        )

    @staticmethod
    def list_records(
        csv_paths: Sequence[Union[str, Path]],
    ) -> List[Tuple[str, int]]:
        records: List[Tuple[str, int]] = []
        for path in csv_paths:
            frame = pd.read_csv(path)
            for row_index in range(len(frame)):
                records.append((str(path), row_index))
        if not records:
            raise ValueError("No DAG records were found.")
        return records

    @staticmethod
    def _max_frequency_entry(
        levels: Sequence[Dict[str, Any]],
        processor: str,
    ) -> Dict[str, float]:
        processor = processor.upper()
        if processor == "A12":
            freq_keys = ("frequency_proc1", "frequency_a12", "frequency")
            time_keys = (
                "utilization_proc1_vf",
                "execution_time_proc1",
                "execution_time_a12",
                "time_a12",
            )
            power_keys = (
                "avg_total_power_proc1",
                "power_proc1",
                "power_a12",
                "total_power_a12",
            )
        elif processor == "A7":
            freq_keys = ("frequency_proc2", "frequency_a7", "frequency")
            time_keys = (
                "utilization_proc2_vf",
                "execution_time_proc2",
                "execution_time_a7",
                "time_a7",
            )
            power_keys = (
                "avg_total_power_proc2",
                "power_proc2",
                "power_a7",
                "total_power_a7",
            )
        else:
            raise ValueError(f"Unknown processor: {processor}")

        candidates: List[Tuple[float, float, float]] = []
        for level in levels:
            try:
                frequency = _get_float(level, freq_keys)
                execution_time = _get_float(level, time_keys)
                power = _get_float(level, power_keys)
            except (KeyError, TypeError, ValueError):
                continue
            if frequency <= 0 or execution_time <= 0 or power <= 0:
                raise ValueError(
                    f"Non-positive {processor} profile: frequency={frequency}, "
                    f"time={execution_time}, power={power}"
                )
            candidates.append((frequency, execution_time, power))

        if not candidates:
            raise ValueError(
                f"Could not extract a valid {processor} profile from v_f_levels."
            )

        frequency, execution_time, power = max(candidates, key=lambda item: item[0])
        return {
            "frequency": float(frequency),
            "execution_time": float(execution_time),
            "power": float(power),
            "energy": float(execution_time * power),
        }

    @staticmethod
    def _legacy_execution_time_profiles(task: Dict[str, Any]) -> Tuple[dict, dict]:
        """
        Minimal compatibility for the professor's original Execution_Time schema.

        It does not contain power, so it cannot support the project's energy reward.
        We reject it with a precise error rather than silently inventing power values.
        """
        execution_entries = task.get("Execution_Time")
        if not execution_entries:
            raise KeyError("Task has neither v_f_levels nor Execution_Time.")
        entry = dict(execution_entries[0])
        a12_time = _get_float(entry, ("utilization_proc1_vf",))
        a7_time = _get_float(entry, ("utilization_proc2_vf",))
        raise ValueError(
            "The supplied task uses legacy Execution_Time-only data. Energy-aware "
            "Gang scheduling also needs A7/A12 power. Regenerate the dataset with "
            "the replacement gen_dataset.py so v_f_levels includes both time and power. "
            f"Observed times: A7={a7_time}, A12={a12_time}."
        )

    def _parse_characteristics(self) -> None:
        for task_id, task in enumerate(self.characteristics):
            period = float(task.get("period", 1.0))
            deadline = float(task.get("implicit_deadline", 0.0))
            m_i = int(task.get("m_i", 1))

            if period <= 0:
                raise ValueError(f"Task {task_id}: period must be positive.")
            if deadline <= 0:
                raise ValueError(f"Task {task_id}: implicit_deadline must be positive.")
            if m_i <= 0:
                raise ValueError(f"Task {task_id}: m_i must be >= 1.")

            levels = task.get("v_f_levels")
            if not isinstance(levels, list) or not levels:
                self._legacy_execution_time_profiles(task)

            a12 = self._max_frequency_entry(levels, "A12")
            a7 = self._max_frequency_entry(levels, "A7")

            self.periods.append(period)
            self.deadlines.append(deadline)
            self.m_i_list.append(m_i)

            self.a7_times.append(a7["execution_time"])
            self.a12_times.append(a12["execution_time"])
            self.a7_powers.append(a7["power"])
            self.a12_powers.append(a12["power"])
            self.a7_energy.append(a7["energy"])
            self.a12_energy.append(a12["energy"])

            self.graph.nodes[task_id].update(
                {
                    "period": period,
                    "implicit_deadline": deadline,
                    "m_i": m_i,
                    "benchmark_name": task.get("benchmark_name", f"task_{task_id}"),
                    "profiles": {
                        "A7": a7,
                        "A12": a12,
                    },
                }
            )
